name: Test and Publish PyTorchLayerViz to PyPI

on:
  push:
    tags:
      - '*'
  workflow_dispatch:      

jobs:
  test-and-publish:
    name: Test and publish PyTorchLayerViz to PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install torch torchvision matplotlib Pillow
    - name: Clean previous builds
      run: |
        rm -rf dist/
    - name: Build a binary wheel
      run: |
        python setup.py sdist bdist_wheel
    - name: Publish PyTorchLayerViz to PyPI
      uses: pypa/gh-action-pypi-publish@v1.5.0
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
