name: Publish PyTorchLayerViz to PyPI

on:
  push:
    tags:
      - '*'

jobs:
  build-n-publish:
    name: Build and publish PyTorchLayerViz to PyPI
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'
    - name: Install build tools
      run: >
        python -m pip install wheel
    - name: Build a binary wheel
      run: >
        python setup.py sdist bdist_wheel
    - name: Publish PyTorchLayerViz to PyPI
      uses: pypa/gh-action-pypi-publish@v1.5.0
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
